edition = "2021"
enum_discrim_align_threshold = 40
# error_on_line_overflow = true
# error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
inline_attribute_width = 80
match_arm_blocks = false
max_width = 80
imports_granularity = "One"
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 40
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
style_edition = "2024"
wrap_comments = true
